dist: xenial

language: python

python:
  - "3.7"
node_js:
  - "10.15.3"

cache:
  directories:
    - node_modules

before_install:
  - pip install -U pip

install:
  - pip install buildbot buildbot-pkg buildbot-worker buildbot-www
  - npm install
  - pip install -e .

script:
  - npm run test
  - npm run lint
